### PR TITLE
Forgot LvControl_RBV archiver tag

### PR DESCRIPTION
**Pull request by aawdls**
I realised I had missed this one which Gary asked for in the last PR

Is there any chance I will be able to make another release so I can get these tags? What other changes are going on?

### CODE REVIEW

**Comment by GDYendell** [comment]
The last release was 16a213f on 15 August. I think everything since then is fairly harmless / Eiger related, so it should be OK. Thoughts, @ajgdls ?

**Comment by ajgdls** [comment]
Yes it looks OK to me.  I would run a quick test before you actually make the release if you are able to, we still have a 1M in lab29 we can use I think (Gary?)

**Review by ajgdls — APPROVED** [review]

**Comment by GDYendell** [comment]
@ajgdls I haven't gotten around to testing my setup, so presumably it is in the state it was in when you left, unless Scott has changed anything.

**Review by GDYendell — APPROVED** [review]

**Comment by aawdls** [comment]
Cool, thanks - for me it will probably be easier to just try it against the J13 3M first since I am working on ti this week

**Comment by ajgdls** [comment]
Oh yes that is even better.  I wasn't sure if it would be possible.

**Pull request merged**
