### PR TITLE
Odin Control updates including Live view

### PR DESCRIPTION
**Pull request by ajgdls**

### CODE REVIEW

**Comment by GDYendell** [comment]
I think $(P)$(R)LiveViewEndpoint should go into the OdinData.template, as it is generic (right?). It would then become (e.g.) EXCALIBUR:ODX:LiveViewEndpoint and we wouldn't need to pass the extra RESET macro to the embedded screen.

**Comment by ajgdls** [comment]
Actually @GDYendell you have spotted a commit that isn't really for the live view.  The reset is to reset FR statistics and unrelated.
The problem with the live view going into OdinData.template is that the live view code is in the detector class, not the odin data classes.  However the PV is generic and so really there should probably be a generic odin detector template, what do you think?

**Comment by ajgdls** [comment]
Although perhaps the reset statistics record should be generic and added to a generic template... I'm not sure because perhaps not all detectors will implement it, but then the reset command would still be available.

**Comment by GDYendell** [comment]
I was meant to copy-and-paste $(P)$(R)$(ADDRESS):ResetStatistics, _not_ $(P)$(R)LiveViewEndpoint, sorry. ResetStatistics should go into OdinData.template.

**Comment by ajgdls** [comment]
@GDYendell  Ah OK yes I agree.  So by doing this the +1 index problem will go away in the edm screens?

**Comment by GDYendell** [comment]
Yep.

**Comment by GDYendell** [comment]
As for whether the live view should go into OdinDetector or OdinDataDriver, I am hoping that they can be recombined into one class again, so that the problem goes away. It doesn't really make sense in OdinDetector because you might not even have an OdinData to talk to. Unless we assume that if you have OdinDetector you will always have OdinData, in which case we should be able to combine them.

So this is fine for now.

**Comment by ajgdls** [comment]
OK @GDYendell moved the record and updated builder/screens.

**Comment by ajgdls** [comment]
Hi @GDYendell can I merge this or do you want to review further?

**Pull request closed without merging**
