### PR TITLE
Add some archiver tags for Excalibur FP status

### PR DESCRIPTION
**Pull request by aawdls**

### CODE REVIEW

**Comment by GDYendell** [comment]
I would say this needs rebasing, but that may not work because the change it needs rebasing on is renaming the files. This might need manually redoing on the latest dls-master on GitHub.

**Comment by GDYendell** [comment]
While we're doing this, could we add:

- OdinData: Writing_RBV, TimeoutActive_RBV
- ExcaliburDetector: ArrayCounter_RBV, ArrayRateRaw_RBV
- ExcaliburFemStatus: FemFrames (I don't know why this isn't an _RBV), CalibrationStatus_RBV
- ExcaliburHouseKeepingStatus: LvControl_RBV

**Comment by ajgdls** [comment]
OK you are right @GDYendell lets manually apply the changes to the new files.  @aawdls is that OK?  The template files were renamed as part of ongoing improvements/tidy up of the module.

**Comment by aawdls** [comment]
That's fine - sorry I must have started working from the wrong point, still getting savvy with git.

**Comment by aawdls** [comment]
I've rebased and added Gary's extra tags

**Review by ajgdls — APPROVED** [review]

**Review by GDYendell — APPROVED** [review]

**Pull request merged**
